name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
      - name: Install modules
        run: npm ci

  build:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Build production project
        run: npm run build:prod
        continue-on-error: true

  lint:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Lint TypeScript
        run: npm run lint:ts
        continue-on-error: true
      - name: Lint CSS
        run: npm run lint:scss
        continue-on-error: true

  test:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Unit testing
        run: npm run test:unit
        continue-on-error: true

  storybook:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Build Storybook
        run: npm run storybook:build
        continue-on-error: true

  ui-test:
    needs: storybook
    runs-on: macos-latest
    steps:
      - name: Screenshot testing
        run: npm run test:ui:ci
        continue-on-error: true
